name: Terraform

on:
  push:
    branches:
      - main
    paths:
      - terraform/*
  pull_request:

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    permissions: write-all
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check --recursive

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color
        continue-on-error: true
      
      - name: tflint-reviewdog
        uses: reviewdog/action-tflint@master
        with:
          github_token: ${{ secrets.github_token }}
          tflint_init: true
          reporter: github-pr-review
          working_directory: terraform
          filter_mode: "nofilter" # Optional. Check all files, not just the diff

      - name: Run Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform
          framework: terraform
          compact: true
          soft_fail: true
          quiet: true
          output_format: cli,junitxml
          output_file_path: console,results.junitxml
    
      - name: Publish Checkov Report
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: 'results.junitxml'
          detailed_summary: true
          check_name: Checkov Report Terraform

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
